import '../../models/food_item.dart';
import '../../models/student.dart';
import '../../models/order.dart';

class MockData {
  static Student get currentStudent => Student(
    id: 'student_123',
    name: 'Aryan',
    studentId: '2023CSB1042',
    email: 'aryan@college.edu',
  );

  static bool get isReturningUser => true; // Set to false to see New User state


  static List<FoodItem> get menuItems => [
    // SANDWICHES
    FoodItem(
      id: 'sw_01',
      name: 'Veg Grilled Sandwich',
      category: 'Sandwiches',
      description: 'Classic grilled sandwich with mixed vegetables',
      price: 50.0,
      prepTime: 10,
      isAvailable: true,
      imageUrl: 'assets/images/sandwich.png',
    ),
    FoodItem(
      id: 'sw_02',
      name: 'Veg Cheese Grilled Sandwich',
      category: 'Sandwiches',
      description: 'Loaded with cheese and mixed vegetables',
      price: 60.0,
      prepTime: 10,
      isAvailable: true,
      imageUrl: 'assets/images/sandwich.png',
    ),
    FoodItem(
      id: 'sw_03',
      name: 'Chicken Grilled Sandwich',
      category: 'Sandwiches',
      description: 'Grilled sandwich with spiced chicken filling',
      price: 70.0,
      prepTime: 12,
      isAvailable: true,
      imageUrl: 'assets/images/sandwich.png',
    ),
    FoodItem(
      id: 'sw_04',
      name: 'Chicken Cheese Grilled Sandwich',
      category: 'Sandwiches',
      description: 'Chicken and melted cheese grilled to perfection',
      price: 85.0,
      prepTime: 12,
      isAvailable: true,
      imageUrl: 'assets/images/sandwich.png',
    ),
    FoodItem(
      id: 'sw_05',
      name: 'Paneer Grilled Sandwich',
      category: 'Sandwiches',
      description: 'Grilled sandwich with seasoned paneer',
      price: 75.0,
      prepTime: 12,
      isAvailable: false, // Testing out of stock
      imageUrl: 'assets/images/sandwich.png',
    ),
    // DESI BITE BITES
    FoodItem(
      id: 'db_01',
      name: 'Veg Roll',
      category: 'Desi Bite Bites',
      description: 'Spicy mixed vegetable wrap',
      price: 70.0,
      prepTime: 12,
      isAvailable: true,
      imageUrl: 'assets/images/roll.png',
    ),
    FoodItem(
      id: 'db_02',
      name: 'Veg Cheese Roll',
      category: 'Desi Bite Bites',
      description: 'Veggie wrap with extra cheese',
      price: 85.0,
      prepTime: 12,
      isAvailable: true,
      imageUrl: 'assets/images/roll.png',
    ),
    FoodItem(
      id: 'db_03',
      name: 'Chicken Roll',
      category: 'Desi Bite Bites',
      description: 'Classic chicken roll with onions and sauces',
      price: 90.0,
      prepTime: 15,
      isAvailable: true,
      imageUrl: 'assets/images/roll.png',
    ),
    FoodItem(
      id: 'db_04',
      name: 'Double Egg Chicken Roll',
      category: 'Desi Bite Bites',
      description: 'Chicken roll wrapped in a double egg paratha',
      price: 90.0,
      prepTime: 15,
      isAvailable: true,
      imageUrl: 'assets/images/roll.png',
    ),
    FoodItem(
      id: 'db_05',
      name: 'Egg Chicken Roll',
      category: 'Desi Bite Bites',
      description: 'Chicken roll wrapped in an egg paratha',
      price: 85.0,
      prepTime: 15,
      isAvailable: true,
      imageUrl: 'assets/images/roll.png',
    ),
    FoodItem(
      id: 'db_06',
      name: 'Chicken Cheese Roll',
      category: 'Desi Bite Bites',
      description: 'Chicken roll loaded with melted cheese',
      price: 110.0,
      prepTime: 15,
      isAvailable: false, // Testing out of stock
      imageUrl: 'assets/images/roll.png',
    ),
    FoodItem(
      id: 'db_07',
      name: 'Egg Roll',
      category: 'Desi Bite Bites',
      description: 'Simple and delicious egg paratha wrap',
      price: 70.0,
      prepTime: 10,
      isAvailable: true,
      imageUrl: 'assets/images/roll.png',
    ),
    FoodItem(
      id: 'db_08',
      name: 'Paneer Roll',
      category: 'Desi Bite Bites',
      description: 'Spiced paneer cubes wrapped in a paratha',
      price: 100.0,
      prepTime: 12,
      isAvailable: true,
      imageUrl: 'assets/images/roll.png',
    ),
    // OMELETTE'S
    FoodItem(
      id: 'om_01',
      name: 'Masala Omelette',
      category: 'Omelette\'s',
      description: 'Fluffy omelette with onions, chilies, and spices',
      price: 35.0,
      prepTime: 7,
      isAvailable: true,
      imageUrl: 'assets/images/omelette.png',
    ),
    FoodItem(
      id: 'om_02',
      name: 'Bread Omelette',
      category: 'Omelette\'s',
      description: 'Classic masala omelette served with toasted bread',
      price: 50.0,
      prepTime: 8,
      isAvailable: true,
      imageUrl: 'assets/images/omelette.png',
    ),
    FoodItem(
      id: 'om_03',
      name: 'Cheese Bread Omelette',
      category: 'Omelette\'s',
      description: 'Bread omelette topped with melted cheese',
      price: 60.0,
      prepTime: 10,
      isAvailable: true,
      imageUrl: 'assets/images/omelette.png',
    ),
    // JUICE'S
    FoodItem(
      id: 'ju_01',
      name: 'Banana Fresh Juice',
      category: 'Juice\'s',
      description: 'Fresh and thick banana juice',
      price: 60.0,
      prepTime: 5,
      isAvailable: true,
      imageUrl: 'assets/images/juice.png',
    ),
    FoodItem(
      id: 'ju_02',
      name: 'Muskmelon Fresh Juice',
      category: 'Juice\'s',
      description: 'Refreshing muskmelon juice',
      price: 60.0,
      prepTime: 5,
      isAvailable: true,
      imageUrl: 'assets/images/juice.png',
    ),
    FoodItem(
      id: 'ju_03',
      name: 'Watermelon Fresh Juice',
      category: 'Juice\'s',
      description: 'Chilled watermelon juice, perfect for summer',
      price: 60.0,
      prepTime: 5,
      isAvailable: false, // Testing out of stock
      imageUrl: 'assets/images/juice.png',
    ),
    FoodItem(
      id: 'ju_04',
      name: 'Grape Fresh Juice',
      category: 'Juice\'s',
      description: 'Freshly squeezed grape juice',
      price: 70.0,
      prepTime: 5,
      isAvailable: true,
      imageUrl: 'assets/images/juice.png',
    ),
    // DOSA'S
    FoodItem(
      id: 'do_01',
      name: 'Plain Dosa',
      category: 'Dosa\'s',
      description: 'Crispy thin plain dosa served with chutney',
      price: 40.0,
      prepTime: 8,
      isAvailable: true,
      imageUrl: 'assets/images/dosa.png',
    ),
    FoodItem(
      id: 'do_02',
      name: 'Egg Dosa',
      category: 'Dosa\'s',
      description: 'Dosa cooked with a layer of beaten egg',
      price: 50.0,
      prepTime: 10,
      isAvailable: true,
      imageUrl: 'assets/images/dosa.png',
    ),
    FoodItem(
      id: 'do_03',
      name: 'Double Egg Dosa',
      category: 'Dosa\'s',
      description: 'Extra thick and rich double egg dosa',
      price: 60.0,
      prepTime: 12,
      isAvailable: true,
      imageUrl: 'assets/images/dosa.png',
    ),
    FoodItem(
      id: 'do_04',
      name: 'Onion Dosa',
      category: 'Dosa\'s',
      description: 'Crispy dosa filled with chopped onions',
      price: 50.0,
      prepTime: 10,
      isAvailable: true,
      imageUrl: 'assets/images/dosa.png',
    ),
    // HOT BEVERAGE'S
    FoodItem(
      id: 'hb_01',
      name: 'Coffee',
      category: 'Hot Beverage\'s',
      description: 'Hot filter coffee',
      price: 30.0,
      prepTime: 5,
      isAvailable: true,
      imageUrl: 'assets/images/coffee.png',
    ),
    FoodItem(
      id: 'hb_02',
      name: 'Cardamom Tea',
      category: 'Hot Beverage\'s',
      description: 'Aromatic tea infused with cardamom',
      price: 25.0,
      prepTime: 5,
      isAvailable: true,
      imageUrl: 'assets/images/tea.png',
    ),
    FoodItem(
      id: 'hb_03',
      name: 'Masala Tea',
      category: 'Hot Beverage\'s',
      description: 'Spiced Indian milk tea',
      price: 25.0,
      prepTime: 5,
      isAvailable: true,
      imageUrl: 'assets/images/tea.png',
    ),
    FoodItem(
      id: 'hb_04',
      name: 'Lemon Tea',
      category: 'Hot Beverage\'s',
      description: 'Refreshing black tea with lemon',
      price: 25.0,
      prepTime: 5,
      isAvailable: true,
      imageUrl: 'assets/images/tea.png',
    ),
    FoodItem(
      id: 'hb_05',
      name: 'Hot Milk',
      category: 'Hot Beverage\'s',
      description: 'Plain hot milk',
      price: 30.0,
      prepTime: 5,
      isAvailable: true,
      imageUrl: 'assets/images/tea.png',
    ),
  ];



  static List<FoodItem> get popularItems => [
    menuItems.firstWhere((i) => i.name == 'Veg Grilled Sandwich'),
    menuItems.firstWhere((i) => i.name == 'Chicken Roll'),
    menuItems.firstWhere((i) => i.name == 'Plain Dosa'),
    menuItems.firstWhere((i) => i.name == 'Masala Omelette'),
  ];

  static List<FoodItem> get studentOrderHistory => [
    menuItems.firstWhere((i) => i.name == 'Veg Grilled Sandwich'),
    menuItems.firstWhere((i) => i.name == 'Veg Grilled Sandwich'),
    menuItems.firstWhere((i) => i.name == 'Coffee'),
    menuItems.firstWhere((i) => i.name == 'Chicken Roll'),
    menuItems.firstWhere((i) => i.name == 'Veg Grilled Sandwich'),
    menuItems.firstWhere((i) => i.name == 'Coffee'),
  ];

  static List<AppOrder> get orderHistory => [
    AppOrder(
      id: 'order_old_1',
      orderNumber: 'ORD-119',
      items: [
        OrderItem(foodItemName: 'Sandwich', quantity: 1, priceAtTime: 50),
        OrderItem(foodItemName: 'French Fries', quantity: 1, priceAtTime: 60),
      ],
      totalAmount: 110.0,
      status: OrderStatus.completed,
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
  ];
}
